### PR TITLE
send an message/event saying the startup sequence has completed or failed

### LINKED ISSUE #307: [BUG] Startup Sequence "Fails" on Any Sequence Being Cancelled
### Short summary

The StartupManager respond and emits an event whenever a sequence completes on the cmdSequencer

### Steps to reproduce

1. Start a sequence on the cmdSequencer
2. Cancel it
3. Observe a Startup Failure Message

### Expected behavior

No message is emitted unless it is actually the startup sequence being cancelled or change this around so that it is just saying that a sequence ended before it was complete. We don't want to confuse users with a "Startup Sequence Failed" message when it's not actually the startup sequence in action.

### Actual behavior

Any time there is sequence activity on the cmdSequencer there are events emitted by this block of code.
```cpp
void StartupManager ::completeSequence_handler(FwIndexType portNum,
                                               FwOpcodeType opCode,
                                               U32 cmdSeq,
                                               const Fw::CmdResponse& response) {
    // Respond to the completion status of the start-up sequence
    if (response == Fw::CmdResponse::OK) {
        this->log_ACTIVITY_LO_StartupSequenceFinished();
    } else {
        this->log_WARNING_LO_StartupSequenceFailed(response);
    }
}
```

### Logs / crash output

_No response_

### Target board

RP2350 (Pico 2)

### PR DESCRIPTION
**Pull request by jordaneburton**
# Send Event Logs for Whether the Startup Sequence has Completed or Failed

## Description
This pull request enhances the `StartupManager` component by improving the handling and logging of start-up sequences. The main changes include adding support for tracking when a sequence begins, and updating the component's internal state to store sequence file path.

* Added a new input port `sequenceStarted` for receiving notifications when a start-up sequence begins, and implemented the corresponding handler method `sequenceStarted_handler`. This handler stores the file name of the sequence being run. 
* Updated the deployment topology to connect the new `sequenceStarted` port between `cmdSeq` and `startupManager`.
* Added a new event `StartupSequenceStarted` to log when a start-up sequence is initiated.
* Added a member variable `m_sequence_file` to `StartupManager` to keep track of the currently running sequence file.
* Enhanced the `completeSequence_handler` to log the completion status of the start-up sequence based on the stored sequence filepath and the command response.

## Related Issues/Tickets

Closes #307 

## How Has This Been Tested?

Tested on a brand new board. Here's event logs from the test:
- [x] Sequence outputs message on successful completion
- [x] Sequence outputs error message on unsuccessful completion
cmdSeqFinished
cmdSeqErrorsOut

## Checklist

- [ ] Written detailed sdd with requirements, channels, ports, commands, telemetry defined and correctly formatted and spelled
- [ ] Have written relevant integration tests and have documented them in the sdd
- [ ] Have done a code review with
- [ ] Have tested this PR on every supported board with correct board definitions

### CODE REVIEW

File: PROVESFlightControllerReference/Components/StartupManager/StartupManager.cpp [hunk 1]
```diff
@@ -151,12 +151,9 @@ void StartupManager ::completeSequence_handler(FwIndexType portNum,
...
                                                U32 cmdSeq,
                                                const Fw::CmdResponse& response) {
-    // Respond to the completion status of the start-up sequence
-    if (response == Fw::CmdResponse::OK) {
-        this->log_ACTIVITY_LO_StartupSequenceFinished();
-    } else {
-        this->log_WARNING_LO_StartupSequenceFailed(response);
-    }
+    // Emits a redudant message indicating the start-up sequence has started on the first completeSequence call
+    this->log_ACTIVITY_LO_StartupSequenceStarted();
```
Comment (nateinaction) [inline PROVESFlightControllerReference/Components/StartupManager/StartupManager.cpp]: This says sequence started but only runs when sequences complete.

File: PROVESFlightControllerReference/Components/StartupManager/StartupManager.fpp [hunk 2]
```diff
@@ -23,7 +26,12 @@ module Components {
         telemetry QuiescenceEndTime: Fw.TimeValue update on change
 
         @ Event emitted when getting boot count
-        event CurrentBootCount(i: I64) severity activity low format "Current boot count: {}"
+        event CurrentBootCount(i: I64) severity activity low \
+            format "Current boot count: {}"
+
+        @ Event emitted when running the start-up sequence
+        event StartupSequenceStarted() severity activity low \
+            format "Start-up sequence started"
```
Comment (nateinaction) [inline PROVESFlightControllerReference/Components/StartupManager/StartupManager.fpp]:
```suggestion
```

Let's delete this unused event.

File: PROVESFlightControllerReference/ReferenceDeployment/Top/topology.fpp [hunk 3]
```diff
@@ -208,8 +208,9 @@ module ReferenceDeployment {
       loraRetry.comStatusOut -> downlinkDelay.comStatusIn
       downlinkDelay.comStatusOut ->ComCcsdsLora.framer.comStatusIn
 
-
+      # add the port
```
Comment (nateinaction) [inline PROVESFlightControllerReference/ReferenceDeployment/Top/topology.fpp]:
```suggestion
```

It looks like this is a left over note, let's remove it.

**Review by nateinaction — COMMENTED** [review]
Looks great! Just a little clean up and we can get it in!

**Review by nateinaction — APPROVED** [review]

**Review by Mikefly123 — APPROVED** [review]
LGTM!
